# This is a basic workflow to help you get started with Actions

name: Download File

# Controls when the workflow will run
permissions:
  contents: write
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '0 * * * *'  # Runs every hour

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Download Excel File
        run: |
          curl -L -o ineligible_voters.xlsx https://vote.phila.gov/media/2024_General_Election_Deficiency_List.xlsx

      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ineligible_voters.xlsx
          git commit -m 'Add updated ineligible_voters.xlsx'
          git push
